-- MySQL Script generated by MySQL Workbench
-- Sat Jun  6 12:09:52 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineeri

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`type_membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_users` (
  `idtype_membre` INT NOT NULL AUTO_INCREMENT,
  `nomType` VARCHAR(45) NULL,
  `default_modify_categories` TINYINT(1) NULL,
  `default_modify_user` TINYINT(1) NULL,
  `default_modify_page` TINYINT(1) NULL,
  `default_modify_commentaire` TINYINT(1) NULL,
  `default_modify_media` TINYINT(1) NULL,
  PRIMARY KEY (`idtype_membre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idmembre` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(55) NOT NULL,
  `email` VARCHAR(210) NOT NULL,
  `date_inscription` DATETIME NOT NULL,
  `password` VARCHAR(40) NULL,
  `type_membre_idtype_membre` INT NOT NULL,
  `can_modify_categories` TINYINT(1) NULL,
  `can_modify_user` TINYINT(1) NULL,
  `can_modify_page` TINYINT(1) NULL,
  `can_modify_commentaire` TINYINT(1) NULL,
  `can_modify_media` TINYINT(1) NULL,
  PRIMARY KEY (`idmembre`),
  INDEX `fk_membre_type_membre1_idx` (`type_membre_idtype_membre` ASC),
  CONSTRAINT `fk_membre_type_membre1`
    FOREIGN KEY (`type_membre_idtype_membre`)
    REFERENCES `mydb`.`type_membre` (`idtype_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`page` (
  `idpage` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `contenu` TEXT NULL,
  `statut` VARCHAR(45) NULL,
  `meta_title` VARCHAR(45) NULL,
  `meta_description` VARCHAR(45) NULL,
  `date_publication` DATETIME NULL,
  `date_last_modification` DATETIME NULL,
  `type_page` VARCHAR(45) NULL,
  `membre_idmembre` INT NOT NULL,
  PRIMARY KEY (`idpage`),
  INDEX `fk_page_membre1_idx` (`membre_idmembre` ASC),
  CONSTRAINT `fk_page_membre1`
    FOREIGN KEY (`membre_idmembre`)
    REFERENCES `mydb`.`membre` (`idmembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `idcategorie` INT NOT NULL AUTO_INCREMENT,
  `nom_categorie` VARCHAR(150) NULL,
  PRIMARY KEY (`idcategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`page_categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`page_categorie` (
  `idpage_categorie` INT NOT NULL AUTO_INCREMENT,
  `page_idpage` INT NOT NULL,
  `categorie_idcategorie` INT NOT NULL,
  PRIMARY KEY (`idpage_categorie`),
  INDEX `fk_page_categorie_page1_idx` (`page_idpage` ASC),
  INDEX `fk_page_categorie_categorie1_idx` (`categorie_idcategorie` ASC),
  CONSTRAINT `fk_page_categorie_page1`
    FOREIGN KEY (`page_idpage`)
    REFERENCES `mydb`.`page` (`idpage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_page_categorie_categorie1`
    FOREIGN KEY (`categorie_idcategorie`)
    REFERENCES `mydb`.`categorie` (`idcategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentaire` (
  `idcommentaire` INT NOT NULL AUTO_INCREMENT,
  `texte` TEXT NULL,
  `date_publication` DATETIME NULL,
  `page_idpage` INT NOT NULL,
  `membre_idmembre` INT NOT NULL,
  PRIMARY KEY (`idcommentaire`),
  INDEX `fk_commentaire_page_idx` (`page_idpage` ASC),
  INDEX `fk_commentaire_membre1_idx` (`membre_idmembre` ASC),
  CONSTRAINT `fk_commentaire_page`
    FOREIGN KEY (`page_idpage`)
    REFERENCES `mydb`.`page` (`idpage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_membre1`
    FOREIGN KEY (`membre_idmembre`)
    REFERENCES `mydb`.`membre` (`idmembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `idmedia` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `type` VARCHAR(45) NULL,
  `emplacement` VARCHAR(255) NULL,
  `page_idpage` INT NOT NULL,
  PRIMARY KEY (`idmedia`),
  INDEX `fk_media_page1_idx` (`page_idpage` ASC),
  CONSTRAINT `fk_media_page1`
    FOREIGN KEY (`page_idpage`)
    REFERENCES `mydb`.`page` (`idpage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
